Completed Unit Test: Loads Comments on First Render
Safewaan/HonkedIn pull request #33
Opened 2023-02-23 21:37 UTC by Eshah7

Tests if the comments render when the page loads!

## Trello ticket link
N/A

## Implementation description
* Created a ForumTest page to bypass the restrictions imposed by Firebase's API
* Created a test to see if the comments render upon the creation of the page for a forum (id = 1 for this purpose) 

## Steps to test
1. npm run test in Terminal

## What should reviewers focus on?
* The tests pass: 
![image](https://user-images.githubusercontent.com/67078410/221035775-e9e9be4d-0e29-403c-b450-11bc115cd357.png)

2023-02-23 22:11 UTC, Safewaan requested changes

2023-02-23 22:11 UTC, safchow commented on src/tests/getForumCommentsByForumID.spec.js
> +    expect(loadGetForumCommentsByForumID).toHaveBeenCalled();
add a few more tests -> a lot of them are reusable and require one/two line changes, look at the tests in https://github.com/Safewaan/HonkedIn/pull/32 for reference

2023-02-25 19:09 UTC, Eshah7 commented on src/tests/getForumCommentsByForumID.spec.js
> +    expect(loadGetForumCommentsByForumID).toHaveBeenCalled();
Re-requested review to merge the one working unit-test for now - thanks!

2023-02-25 21:49 UTC, Safewaan commented on package.json
> +    "fetch-mock": "^9.11.0",
note for next time: please double check any added dependencies if they're being used

this dependency is not being used so it should be removed from `package.json` and `package-lock.json` but I'll clean this up once all PRs are merged

2023-02-25 21:49 UTC, Safewaan commented on src/componentsTest/ForumTest.js
> +import React, { useRef, useState, useEffect } from "react"
this file should retain its original name: `Forum.js`

2023-02-25 21:49 UTC, Safewaan commented on src/tests/getForumCommentsByForumID.spec.js
> +import React from 'react';
This file should be called `Forum.test.js`

2023-02-25 21:49 UTC, Safewaan commented on src/componentsTest/ForumTest.js
> +                            <Typography sx={{ mb: 1.5 }} color="text.secondary">
remove the `color=text.secondary` styling from all components as it throws a warning during test runs

2023-02-25 21:49 UTC, Safewaan approved these changes

2023-02-25 21:53 UTC, merged