Gabbytang/search events
Safewaan/HonkedIn pull request #56
Opened 2023-03-16 02:41 UTC by gabbytang

## Trello ticket link

[As a user, I can search for events so that I can find relevant topics.][(https://trello.com/b/RCwqUZD8/msci-342-scrum-board](https://trello.com/c/6tWLDA45) )

## Implementation description
* Implemented search feature to the events page
* Users can now type anything in the search bar and get a resulting list events that have either names, description, or creators that match the search term. 
* Created Search and SubmitButton components to be imported into other components. 

## Steps to test
1. Ensure the search field is open to any text value 
2. Clicking the search button should render the list of all events that match the input search term 
3. If nothing is entered in the search bar, the whole list of events in the db should be rendered
4. The search function should match an event by either name, description, or creator name

## What should reviewers focus on?
* The search function is accurate
* If there are no matches for a search, the page should be empty

2023-03-17 15:28 UTC, Eshah7 requested changes
Looks good!

Just a couple of questions: 

Why does Eng Student Working show up when I type in Te? 
<img width="862" alt="Screenshot 2023-03-17 at 11 26 40 AM" src="https://user-images.githubusercontent.com/67078410/225948673-67dc5092-961b-4980-a3c1-f152f346155d.png">

Also, I was wondering if we should say "Search for events by name or user name" so that users know that both are possible separately? 

Thanks!

2023-03-17 16:08 UTC, Eshah7 approved these changes
LGTM!

2023-03-17 17:02 UTC, Safewaan reviewed
everything looks good!

In terms of the search functionality, what are your thoughts on adding a "Reset" or "Reset Search" option? The two ways to do this currently are to refresh the page or to search again but with no filter, which may not be intuitive for the user.

2023-03-17 17:02 UTC, safchow commented on src/components/common/Search.js
> +import TextField from '@material-ui/core/TextField';
nice! making these reusable is good practice 👍

2023-03-18 20:30 UTC, Safewaan requested changes

2023-03-18 20:30 UTC, Safewaan commented on src/components/events/Events.js
> +        <Search
We should consider adding these searches to the "My ..." (ex "My Events") as well for consistency

2023-03-18 23:38 UTC, Safewaan approved these changes
lgtm! Eventually we're going to need to style the search component (updating font, changing button colour, etc.) so its great that you made it a reusable component 👍 

As for when to style it, you can style it with this PR or merge this in and we can revisit styling later. Up to you. If you want to style it now, I can give you a walkthrough of CSS and Chakra UI whenever you're ready

2023-03-18 23:55 UTC, merged