Styling for the Navigation Bar
Safewaan/HonkedIn pull request #57
Opened 2023-03-17 16:36 UTC by Safewaan

## Trello ticket link

[Developer Task: Implement UI/UX feedback to the navigation bar](https://trello.com/c/5IA61xjQ/119-developer-task-implement-ui-ux-feedback-to-the-navigation-bar )

## Implementation description
* Added new component framework, Chakra UI
* Rebuilt the Navigation Bar

## Steps to test
1. Verify that all menu options open their corresponding menu lists
2. Verify that each menu list option routes to the correct page
3. Verify there are no visual conflicts with other pages

## What should reviewers focus on?
* Are there colour schemes we should adopt? Fonts and font sizes?

2023-03-18 20:41 UTC, gabbytang requested changes
The styling is a major improvement from what we had before, its so aesthetically pleasing to look at the menu options. There was one major issues I was getting which tbh doesn't match the changes you've made. You should take a look if you are getting the same issues, because often times after completing a function, the screen doesn't reload, and is instead a blank screen.

2023-03-18 20:41 UTC, gabbytang commented on src/components/events/Events.js
When I try to join an event, the page doesn't give a toast message or reload. It just goes completely blank. It doesn't matter if I'm already a participant or not.
If I manually reload the webpage, it appears Im still able to join the list of participants.

2023-03-18 20:41 UTC, gabbytang commented on src/components/events/Events.js
I know you didn't make any changes to the file itself, but the screen also goes blank after I create an event.

2023-03-18 20:41 UTC, gabbytang commented on src/components/forums/MyForums.js
Screen also goes blank when I try to archive a forum. There;s something screwing with some window reloads, but only in some cases. When I added a comment to a forum the page reloaded just fine, with no errors.

2023-03-18 20:41 UTC, gabbytang commented on src/components/common/NavigationBar.js
> -                                    HonkedIn
As a UI aspect thats typical in a lot of cases, what do you think about linking the home page to the "HonkedIn" logo/word also. As in keep the home button, but also link home in the logo. I think LinkedIn does that

2023-03-18 20:41 UTC, gabbytang commented on src/components/resources/Resources.js
Getting same reload error for creation of a resource

2023-03-18 20:59 UTC, Safewaan commented
> When I try to join an event, the page doesn't give a toast message or reload. It just goes completely blank. It doesn't matter if I'm already a participant or not. If I manually reload the webpage, it appears Im still able to join the list of participants.

> Screen also goes blank when I try to archive a forum. There;s something screwing with some window reloads, but only in some cases. When I added a comment to a forum the page reloaded just fine, with no errors.

> Getting same reload error for creation of a resource

These all seem to be caused by the Alert component, the backend and APIs are still processing requests. There may be a conflict with MUI Alert and the Chakra UI framework. Looking into a fix, might possibly need a refactor of the Alert component

2023-03-18 21:40 UTC, Safewaan commented
> > When I try to join an event, the page doesn't give a toast message or reload. It just goes completely blank. It doesn't matter if I'm already a participant or not. If I manually reload the webpage, it appears Im still able to join the list of participants.
> 
> > Screen also goes blank when I try to archive a forum. There;s something screwing with some window reloads, but only in some cases. When I added a comment to a forum the page reloaded just fine, with no errors.
> 
> > Getting same reload error for creation of a resource
> 
> These all seem to be caused by the Alert component, the backend and APIs are still processing requests. There may be a conflict with MUI Alert and the Chakra UI framework. Looking into a fix, might possibly need a refactor of the Alert component

@gabbytang Good catch, it was a component framework conflict, fix has been put in. Please verify that all the pages that display Alerts function correctly.

2023-03-18 22:21 UTC, Eshah7 reviewed
Not quite sure how to explain this...

However, when I hover over the "HonkedIn" text, the cursor changes into the "I", editing symbol rather than indicating to the user that they are able to click on the HonkedIn text.

2023-03-18 22:23 UTC, Eshah7 commented
<img width="716" alt="Screenshot 2023-03-18 at 6 22 28 PM" src="https://user-images.githubusercontent.com/67078410/226143295-cb6f9ca6-4888-48ae-b363-91203553d171.png">

Is the toast message supposed to have any space from the bottom, similar to what we had before?

2023-03-18 22:24 UTC, Eshah7 commented
Not sure if this is addressed in the same PR but, I was thinking if we could replace the gear symbol with a silhouette of a person because it is a little confused as to where I can view my "own profile"!

2023-03-18 22:25 UTC, Eshah7 commented
<img width="581" alt="Screenshot 2023-03-18 at 6 24 57 PM" src="https://user-images.githubusercontent.com/67078410/226143374-31014768-fc9b-4933-9933-b4e85cce10f7.png">

Also, I think due to the font change, the spacing for my profile page has been disrupted a little...

2023-03-18 22:26 UTC, Eshah7 commented
Overall, everything else LGTM, it's really pretty!!! Thank you :)

2023-03-18 22:38 UTC, gabbytang commented
> Not sure if this is addressed in the same PR but, I was thinking if we could replace the gear symbol with a silhouette of a person because it is a little confusing as to where I can view my "own profile"!

I actually don't mind the gear, I feel like a lot of sites and apps have edit profile under settings.

2023-03-18 22:39 UTC, gabbytang commented
> Not quite sure how to explain this...
> 
> However, when I hover over the "HonkedIn" text, the cursor changes into the "I", editing symbol rather than indicating to the user that they are able to click on the HonkedIn text.

Yeah, when you hover over the HonkedIn icon the cursor is not a finger pointing which typically is what indicates a link.

2023-03-18 22:40 UTC, gabbytang commented
Once you implement Esha's changes, i think everything looks great. Nice work on cleaning up our nav bar, it really makes our site look more professional

2023-03-18 22:40 UTC, gabbytang approved these changes

2023-03-18 23:30 UTC, Safewaan commented
> <img alt="Screenshot 2023-03-18 at 6 22 28 PM" width="716" src="https://user-images.githubusercontent.com/67078410/226143295-cb6f9ca6-4888-48ae-b363-91203553d171.png">
> 
> Is the toast message supposed to have any space from the bottom, similar to what we had before?

its currently fixed to the bottom right, I can add margins from the corners if that's preferred

2023-03-18 23:31 UTC, Safewaan commented
> Not quite sure how to explain this...
> 
> However, when I hover over the "HonkedIn" text, the cursor changes into the "I", editing symbol rather than indicating to the user that they are able to click on the HonkedIn text.

I changed the component to a Link, let me know if this fixes the issue

2023-03-18 23:33 UTC, Safewaan commented
> <img alt="Screenshot 2023-03-18 at 6 24 57 PM" width="581" src="https://user-images.githubusercontent.com/67078410/226143374-31014768-fc9b-4933-9933-b4e85cce10f7.png">
> 
> Also, I think due to the font change, the spacing for my profile page has been disrupted a little...

This isn't related to the font change, as only the navbar's font has been updated. It's being caused by this:
```
            <Box sx={{ position: 'absolute', top: 240, left: "35%" }} >
```

Updating how many pixels this component should render from the top should resolve this issue, but this page needs a UI overhaul, so it can be addressed then

2023-03-19 16:41 UTC, Eshah7 commented
> > <img alt="Screenshot 2023-03-18 at 6 22 28 PM" width="716" src="https://user-images.githubusercontent.com/67078410/226143295-cb6f9ca6-4888-48ae-b363-91203553d171.png">
> > Is the toast message supposed to have any space from the bottom, similar to what we had before?
> 
> its currently fixed to the bottom right, I can add margins from the corners if that's preferred

I think margins would be nice, however not really a high priority! Thank you :)

2023-03-19 16:41 UTC, Eshah7 commented
> > Not quite sure how to explain this...
> > However, when I hover over the "HonkedIn" text, the cursor changes into the "I", editing symbol rather than indicating to the user that they are able to click on the HonkedIn text.
> 
> I changed the component to a Link, let me know if this fixes the issue

Fixed! Thanks :)

2023-03-19 16:43 UTC, Eshah7 approved these changes
Lgtm!

2023-03-20 02:24 UTC, merged