Style Events and My Events Page
Safewaan/HonkedIn pull request #78
Opened 2023-03-25 23:41 UTC by Safewaan

## Trello ticket link

[Developer Task: Implement user feedback for UI/UX of Events Page](https://trello.com/c/vNs8Lr9k/134-developer-task-implement-user-feedback-for-ui-ux-of-events-page)

## Implementation description
* Styled Events and My Events Page
* Styled all dialogue options (View Event, Edit Event, Cancel Event, See Participants)

## Steps to test
1. Verify all dialogue options are working (ex: cancel an event, join an event, verify db is written to)
2. Verify there are no styling inconsistencies
3. Verify correct errors are thrown in error cases

2023-03-25 23:53 UTC, Eshah7 commented
Is it possible to make the cards a bit wider?

2023-03-25 23:56 UTC, Eshah7 commented
Also, I noticed that on my events page, the filter defaults to "Active" - I think we discussed keeping the filter empty for my events, but I do not mind!

2023-03-25 23:56 UTC, Eshah7 approved these changes
lgtm!

2023-03-26 00:04 UTC, gabbytang requested changes
With regards to this implementation, everything looks great, all alerts seem to be working, and the pages are consistent with each other.

There is just one error with the Edit Event form

2023-03-26 00:04 UTC, gabbytang commented on src/components/events/MyEvents.js
I should have caught this previously, but there seems to be an error with the Edit Events form. I can't change the max participants number. Every other field is able to be updated.

2023-03-26 00:24 UTC, Safewaan commented on src/components/events/MyEvents.js
put in a fix- let me know if the issue is resolved

2023-03-26 00:25 UTC, Safewaan commented
> Also, I noticed that on my events page, the filter defaults to "Active" - I think we discussed keeping the filter empty for my events, but I do not mind!

I updated this to keep it consistent with the events page

2023-03-26 00:42 UTC, gabbytang requested changes
You fixed the edit participants amount bug. So everything looks perfect except for one small thing. Should update to "edited" 
<img width="143" alt="image" src="https://user-images.githubusercontent.com/90345332/227749105-3424e7f1-91fa-4067-a6ca-1bb6fab39a5d.png">

2023-03-26 00:45 UTC, gabbytang approved these changes

2023-03-26 00:45 UTC, merged